name: ci.yml
on:
  pull_request: 
    types:
      - opened
      - synchronize
    branches:
      - main
      - develop
  
  push: 
    branches:
      - main
      - develop

env: 
  USER_1: "dwd9999"
  USER_2: "Cutaku"

jobs:
  gradle-clean-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with: 
          java-version: 21
          distribution: corretto
      
      - name: Grant Execute Permission
        run: chmod +x gradlew
        
      - name: Gradle Clean Build
        run: ./gradlew clean build
  
  assign-reviewer:
    needs: gradle-clean-build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - name: Assign reviewer
        uses: actions/github-script@v6
        with: 
          github-token: '${{ github.token }}'
          script: |
            const user1 = process.env.USER_1;
            const user2 = process.env.USER_2;
            const actor = context.actor;
            
            let reviewer = "";
            
            if (actor === user1) {
              reviewer = user2;
            } else if (actor === user2) {
              reviewer = user1;
            } else {
              reviewer = user1;
            }
            
            reviewer = user1;
            
            if (reviewer) {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                reviewers: [reviewer]
              });
              console.log(`Reviewer assigned: ${reviewer}`);
            }
  deploy:
    needs: gradle-clean-build
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Grant Execute Permission
        run: chmod +x gradlew
      
      - name: Gradle Build
        run: ./gradlew clean build -x test
      
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with: 
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/treetory:latest
            ${{ secrets.DOCKER_USERNAME }}/treetory:${{ github.sha }}
      
      - name: Deploy
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            /home/bacinf/treetory/deploy.sh